Exhaustive Research Report on the Jurisprudence, History, and Contemporary Application of Al-Mu'allafatu Qulubuhum in Islamic Law
Introduction to the Institution of Zakat and its Macro-Economic Objectives
In the foundational architecture of Islamic jurisprudence and socio-economic policy, the institution of Zakat occupies a central and non-negotiable position, functioning simultaneously as a mandatory spiritual act of worship and a highly sophisticated mechanism for wealth redistribution.1 Rooted firmly in the Quran and the Sunnah of the Prophet Muhammad, Zakat represents a sacred duty incumbent upon every eligible Muslim, designed to alleviate poverty, ensure equitable wealth circulation, address economic disparities, and stabilize the socio-political fabric of the Muslim community.1 Far from being a mere voluntary charity, Zakat is a formalized, obligatory levy on surplus wealth, serving as a structural pillar of the Islamic economic system intended to regain balance and equilibrium in social and economic life.2
The divine injunction explicitly and restrictively demarcates the beneficiaries of this obligatory almsgiving into eight distinct categories, as articulated in Surah Al-Tawbah (9:60).3 This precise categorization was legislated to prevent the misappropriation of funds and to ensure that the wealth serves specific, divinely ordained socio-political and humanitarian objectives.6 Among these eight categories, al-mu'allafatu qulubuhum—conventionally translated as "those whose hearts are to be reconciled" or "those whose hearts are brought near"—stands out as one of the most dynamic, complex, and heavily debated classifications in classical and modern Islamic legal theory.3 Unlike the categories of the poor or the debt-ridden, which are predicated on absolute material deprivation, the allocation of Zakat to the mu'allafatu qulubuhum transcends simple poverty alleviation.4 It operates at the critical nexus of statecraft, diplomacy, socio-political stabilization, and ideological encouragement.
This category uniquely permits the disbursement of mandatory alms to individuals of significant social standing, tribal authority, or political influence, regardless of their personal wealth, to secure the broader geopolitical and social interests of the Islamic state.4 The historical application by the Prophet Muhammad, the subsequent suspension of the practice by the second Caliph Umar ibn al-Khattab, and the contemporary revival of this category present a fascinating study in the mechanics of Islamic jurisprudence (usul al-fiqh), specifically concerning the identification of the effective cause ('illah) of a legal ruling and its adaptability to changing socio-political realities.9 In the modern era, the conceptual boundaries of al-mu'allafatu qulubuhum have been continuously stretched and tested to address unprecedented challenges, sparking intense scholarly debates regarding its applicability to Western political lobbying, disaster relief for non-Muslims, and institutionalized welfare programs for new converts.11
Lexicographical and Etymological Foundations
To fully comprehend the jurisprudential weight and operational scope of al-mu'allafatu qulubuhum, a rigorous analysis of its etymological and linguistic roots is required. In Islamic legal theory, the linguistic derivation of a term often establishes the parameters of its legal application. The term derives from the Arabic triconsonantal root a-l-f (أ-ل-ف), which carries the primary semantic connotations of bringing together, harmonizing, uniting, and creating a sense of deep affinity where there was previously alienation, indifference, or active discord.14
The historical evolution and stabilization of this definition are best observed in the seminal Arabic lexicon Lisān al-ʿArab, completed by the eminent lexicographer Ibn Manzur in 1290.14 Ibn Manzur's monumental project, which synthesized previous authoritative works such as Azharī’s Tahdhīb al-Lugha, Ibn Sidah’s Al-Muḥkam, and Jauhari’s Ṣiḥāḥ, spans twenty printed volumes and remains the definitive reference for classical Arabic semantics.14 Within this lexicographical tradition, the verb allafa and its derivative ta'lif signify the deliberate act of binding disparate elements into a cohesive, harmonious whole.14 The phrase "reconciling of hearts" (ta'lif al-qulub) therefore implies a strategic, deliberate, and often systematic effort to transform hostility into neutrality, neutrality into active alliance, and tentative alliance into deep-rooted conviction.17
When translated into the realm of Quranic exegesis (tafsir) and public policy, classical scholars meticulously unpacked the implications of this linguistic root. Imam Muhammad ibn Jarir al-Tabari, one of the most authoritative early exegetes, defined this demographic specifically as a group of people who were brought closer to Islam through the explicit incentive of being given wealth.4 Tabari noted that in the formative years of the Islamic polity, the survival of the state required mechanisms to pacify powerful tribal leaders who could not be openly supported or subdued through military means alone.4 Zakat, in this context, served a dual function: while it addressed the material deficiencies of the indigent, it simultaneously functioned as a strategic expenditure to aid and fortify the religion itself by binding the hearts of key influencers to the Muslim community.4 Because the disbursement of funds to the mu'allafatu qulubuhum was intrinsically linked to strengthening the state, repelling harm, and generating political affinity, Tabari and other classical jurists concluded that individuals in this category were eligible to receive Zakat even if they possessed vast personal wealth, as the objective was political harmonization rather than poverty relief.4
The Scriptural Mandate: The Eight Categories of Zakat
The legal framework for the mu'allafatu qulubuhum cannot be analyzed in isolation; it must be understood within the broader architecture of the eight beneficiaries of Zakat explicitly mandated in Surah Al-Tawbah (9:60).3 The verse dictates: "Indeed, [prescribed] charitable offerings are only [to be given] to the poor and the needy, and to those who work on [administering] it, and to those whose hearts are to be reconciled, and to [free] those in bondage, and to the debt-ridden, and for the cause of God, and to the wayfarer. an obligation from God. And God is all-knowing, all-wise".5
The classical exegetes and jurists provided rigorous definitions for each category to ensure precision in state welfare distribution. The first two categories, Al-Fuqara' (the poor) and Al-Masakin (the needy), deal with absolute material deprivation.6 The precise distinction between the two was a matter of scholarly debate, but foundational Hadiths provided the guiding principles. According to a narration recorded by Ahmad, Abu Dawud, and At-Tirmidhi from Ibn Umar, the Prophet Muhammad stated that alms are not lawful for the wealthy or the physically fit.18 To define the Miskin, the Prophet clarified in a Hadith narrated by Abu Hurayrah (recorded by Bukhari and Muslim) that the needy person is not the one who roams around begging for a mouthful or a date; rather, the true Miskin is the one who lacks sufficient means to satisfy their needs, yet their condition remains hidden from the public, preventing them from receiving charity, and they refuse to beg.18
The third category comprises the administrators of Zakat (al-'amilina 'alayha), who are entitled to a portion of the funds as compensation for their labor in collection and distribution.5 However, strict conflict-of-interest regulations applied; a Hadith recorded by Muslim indicates that the Prophet explicitly forbade his own relatives (the family of Muhammad) from serving as Zakat collectors and receiving this wealth, stating that alms represent the "dirt that the people discard".18
The subsequent categories address systemic socio-economic crises. Fir-Riqab involves using Zakat to purchase the freedom of slaves or captives held against their will, representing an institutionalized abolitionist mechanism.1 Al-Gharimin designates the debt-ridden—individuals whose liabilities overwhelmingly exceed their assets, threatening their socio-economic survival.1 Fi Sabilillah (in the cause of God) traditionally referred to the funding of military defense and those fighting for a religious cause who were not receiving a regular state salary.19 Finally, Ibn al-Sabil (the wayfarer) refers to travelers who have become stranded and cut off from their wealth, requiring financial assistance to return home, even if they are wealthy in their native lands.5
Within this intricate framework of poverty alleviation, administrative compensation, debt relief, abolition, military defense, and travel assistance, the fourth category—al-mu'allafatu qulubuhum—stands out as an instrument of community development, political reconciliation, and ideological consolidation.5 It addresses the psychological, political, and social alignment of individuals whose support is deemed critical for the overarching stability and expansion of the Muslim community.5
Historical Precedents in the Prophetic Era
The practical implementation of al-mu'allafatu qulubuhum during the life of the Prophet Muhammad provides the essential, irreplaceable jurisprudential precedent upon which all subsequent Islamic legal rulings are based. During the nascent and highly volatile stages of Islam, the Muslim community in Medina was surrounded by hostile polytheistic tribes and formidable empires. The Prophet utilized wealth as a strategic, diplomatic tool to fracture enemy alliances, reward defection, stabilize newly conquered territories, and ease the ideological transition of prominent leaders into the Islamic faith.20
The most prominent historical manifestation of this practice occurred in the immediate aftermath of the Conquest of Mecca and the subsequent Battle of Hunayn. Following a decisive and highly lucrative victory over the hostile Hawazin and Thaqif tribes, the Prophet acquired unprecedented amounts of spoils.21 Rather than distributing the bulk of this vast wealth to his intensely loyal veteran companions from Medina (the Ansar), the Prophet made a highly strategic geopolitical decision: he allocated massive fortunes to the newly converted, yet still politically influential, aristocrats of Mecca and the surrounding desert tribes, many of whom had fought bitterly against him just weeks prior.4
Historical records preserved by early historians and Hadith scholars detail the astonishing scale of these disbursements. The Prophet granted one hundred she-camels each to prominent tribal chieftains such as Abu Sufyan ibn Harb, Safwan ibn Umayya, 'Uyaynah bin Hisn, and Al-Aqra' bin Habis.4 Other leaders received slightly lesser amounts; for instance, 'Abbas ibn Mirdas initially received fifty camels, prompting a poetic complaint that resulted in the Prophet increasing his share.10 Other notable figures who received significant shares to reconcile their hearts included Hakim bin Hizam, Suhayl bin 'Amr, 'Alqamah bin 'Ulathah, and Zayd al-Khayr.4
To contextualize this within socio-economic terms, a herd of one hundred camels represented an astronomical transfer of wealth—analogous to establishing these leaders as immediate corporate entities or major economic powerhouses in the modern era.4 Safwan ibn Umayya, who was remarkably still a polytheist when he initially received these grants, famously articulated the psychological efficacy of this policy. The Prophet had borrowed Safwan's armory for the expedition of Hunayn and subsequently gifted him an entire valley filled with camels and goods.21 Stunned by the generosity, Safwan remarked that such a gift could only come from someone who did not fear poverty, famously stating: "The Prophet continued giving to me until he went from being the most hated person to me, to the most beloved".4
This historical episode illuminates several profound insights into classical Islamic statecraft and sociological engineering. Firstly, it demonstrates the Prophet's recognition that ideological paradigm shifts within deeply entrenched, honor-based tribal societies often require material catalysts. Wealth was used to bypass ideological resistance and hostility, allowing the recipients the psychological safety and space to evaluate Islam without the defensive posture of a vanquished foe. Secondly, by elevating the economic status of the defeated Meccan elite and peripheral tribal leaders, the Prophet effectively neutralized the threat of internal rebellion and sabotage. The sudden influx of wealth tied their personal economic fortunes directly to the stability and success of the Islamic state. Thirdly, this policy capitalized on the ripple effect of tribal leadership. In highly stratified tribal hierarchies, the allegiances of the masses are inextricably linked to the allegiances of their chieftains. By securing the hearts of the obeyed leaders (sādah muṭāʿūn), the Islamic state indirectly secured the pacification, loyalty, and eventual genuine conversion of thousands of subordinate tribesmen.11
Typological Classifications by Classical Scholars
Drawing from the diverse Prophetic precedents, classical scholars developed highly sophisticated typologies to classify the mu'allafatu qulubuhum. These granular classifications demonstrate that the category was never viewed as a monolith, but rather as a multi-faceted policy tool tailored to address specific geopolitical, social, and psychological dynamics. The renowned exegete Ibn Kathir, synthesizing the actions of the Prophet, delineated five distinct sub-categories of the mu'allafatu qulubuhum, while other scholars like Al-Mawardi offered their own structural views.4
The classical classifications can be synthesized to understand the operational breadth of this category:

Typological Category
Primary Objective of the Disbursement
Classical Historical Precedent
Theological and Political Function
Potential Converts (Non-Muslims)
To encourage submission and formal acceptance of Islam.
Safwan bin Umayyah (who received massive wealth while still a polytheist).
Utilizing immense financial incentives to break down ideological prejudice, demonstrate the economic supremacy and benevolence of the Islamic state, and secure a prominent conversion.4
Weak Muslims (Recent Converts)
To improve and firm their nascent faith, ensuring ideological stability.
The Qurayshi elite post-conquest, such as Abu Sufyan, who required integration.
Preventing apostasy (riddah) among those who accepted Islam for political expediency or out of defeat, ensuring they transition into genuine, committed adherents.4
Tribal Influencers and Chiefs
To encourage peers and massive subordinate populations to submit.
Tribal chiefs whose tribes strictly follow their directives without question.
Leveraging pre-existing tribal hierarchies, kinship structures, and social capital for the mass, frictionless propagation of the faith across vast territories.4
Alms Elicitors (Administrative Aids)
To elicit the payment of Zakat from resistant or distant populations.
Leaders situated in peripheral, semi-autonomous, or geographically isolated regions.
Using a portion of the Zakat funds as a strategic commission-like incentive to ensure the smooth, unopposed collection of state revenues from tribes that might otherwise rebel.4
Border Defenders (Military Proxies)
To ward off external harm and secure the territorial integrity of the state.
Frontier leaders securing the dangerous borderlands surrounding Muslim territory.
Outsourcing border security and military defense to allied or semi-allied populations through financial grants, reducing the burden on the formal state military apparatus.4

Furthermore, scholars meticulously identified the specific tribal confederations targeted by these policies. The classical authority Yahya bin Abi Kathir specifically named the leaders of ten highly influential tribes or clans who were designated as mu'allafatu qulubuhum: Banu Umayyah, Banu Jumah, Banu 'Amir, Banu Asad, Banu Hashim, Banu Fazarah, Banu Tamim, Banu Nasr, Banu Sulaym, and Thaqif.4 Maliki sources, citing the jurist Asbagh from Ibn al-Qasim, noted that this category was heavily concentrated among specific men of the Quraysh, while Shaykh Abu Ishaq identified forty specific men of the Quraysh and allied tribes who comprised this initial cohort of reconciled hearts.4
A critical jurisprudential distinction maintained by classical encyclopedias of Islamic law, such as the Mawsu'a al-Fiqhiyya al-Kuwaytiyya, is the bifurcation of this category into Muslims and non-Muslims.20 While there was broad consensus regarding the eligibility of weak Muslims whose faith needed strengthening, the disbursement of Zakat to non-Muslims—either those whose conversion was hoped for or those whose active hostility was feared—became the epicenter of a major jurisprudential schism immediately following the death of the Prophet.20
The Jurisprudential Paradigm Shift: Umar ibn al-Khattab and Abu Bakr
The flexible application of the mu'allafatu qulubuhum category encountered a significant, historical paradigm shift during the caliphate of Abu Bakr, driven primarily by the profound legal reasoning and political foresight of Umar ibn al-Khattab. This historical juncture birthed one of the most significant debates in Islamic jurisprudence regarding the permanence of textual injunctions versus the dynamism of the 'illah (ratio legis or effective cause of a ruling).
Following the death of the Prophet, during the reign of the first Caliph, Abu Bakr, prominent tribal chiefs 'Uyaynah bin Hisn and Al-Aqra' bin Habis—both of whom had previously received vast sums of wealth from the Prophet—approached the Caliph with a specific request.10 They asked to be granted a specific tract of swamp land that did not grow grass and was seemingly unbeneficial, requesting the right to manage and cultivate it as their ongoing share of the mu'allafat al-qulub.10 Abu Bakr, adhering strictly to the immediate Prophetic precedent, agreed to their request and drafted a formal document granting them the land.10 However, to formalize the decree, he required the testimony and signature of Umar ibn al-Khattab, his most trusted advisor and eventual successor.10
Upon reviewing the document, Umar flatly rejected the request. He physically deleted the contents of Abu Bakr's letter (or tore up the document in some narrations) and issued a stunning rebuke: "Indeed, first the Messenger of Allah gave you a share in order to bind your hearts when Islam was still weak. Now that Allah has glorified Islam, then go and earn a living".10 When 'Uyaynah bin Hisn subsequently confronted Caliph Umar directly seeking alms, Umar further justified his refusal by reciting a verse from Surah Al-Kahf (18:29): "The Truth [has come] from your Lord: so whoever wishes to, may have faith; and whoever wishes to, may deny!".4 By invoking this verse, Umar declared that the Islamic state was no longer in a position of existential weakness that required the financial appeasement of tribal warlords to prevent their defection or secure their neutrality.4
The Analytical Debate among the Four Sunni Schools
Umar's watershed ruling was not viewed by classical scholars as an act of abrogating (naskh) the Quran—a theological impossibility in orthodox Sunni Islam after the cessation of revelation following the Prophet's death. Rather, it was recognized as a masterful, context-driven application of legal reasoning based on the absence of the effective cause ('illah). The differing interpretations of Umar's monumental action led to distinct, codified rulings among the four major schools of Sunni jurisprudence (Madhahib) 23:
1. The Hanafi and Shafi'i Perspectives: Suspension of the Category
The Hanafi and Shafi'i schools largely concluded that the share for non-Muslims and appeased leaders under the mu'allafatu qulubuhum category was effectively nullified or permanently suspended due to the changed geopolitical realities.21 Imam al-Nawawi, a preeminent Shafi'i authority, explicitly stated that Zakat cannot be given to a disbeliever under any circumstance, reflecting a firm consensus within the school that the historical triumph of the Islamic state rendered the appeasement of non-Muslims utterly obsolete.26 According to the Shafi'i school, if no eligible recipients of Zakat can be found within the other categories, the funds should be kept safely until a qualified Muslim recipient becomes available, rather than dispensing them to non-Muslims for reconciliation.26
The prominent Hanafi jurist Al-Jassas provided a deeply structural analysis to support this suspension. He argued that the mu'allafatu qulubuhum were never originally given Zakat because they were personally poor or inherently entitled to it.4 Instead, the funds were a mechanism of state defense utilized for the general benefit (maslahah) of the impoverished Muslims.4 By paying off warlords, the Prophet repelled harm from the vulnerable Muslim populace.4 Once the Islamic state achieved overwhelming geopolitical hegemony, the necessity to repel harm through financial bribery vanished entirely, rendering the allocation invalid and returning those funds to the genuinely poor.4
2. The Maliki and Hanbali Perspectives: Contextual Reactivation
Conversely, the Maliki and Hanbali schools maintained a more fluid interpretation, arguing that the category remains fundamentally lawful, operative, and permanently embedded in Islamic law, albeit subject to circumstantial necessity.22 They argued that the cessation of payments during Umar's era was purely circumstantial, reflecting a specific period of strength, not a permanent abrogation of a Quranic mandate.27
The great Maliki jurist Qadi Abu Bakr ibn al-'Arabi provided a definitive, dynamic synthesis of this view. He argued that if the Islamic state is strong, dominant, and unchallenged, this category naturally lies dormant, and the designated funds are redistributed to the other seven categories of Zakat.4 However, if the state faces sudden weakness, external threats, or if a specific geopolitical need arises that requires the alignment of neutral or hostile parties, the Imam (ruler) is fully authorized to reactivate the category and dispense funds just as the Prophet did.4 Ibn al-'Arabi powerfully supported this cyclical view of history by citing the authentic Prophetic tradition: "Islam began as a stranger, and will return as a stranger, as it began".4 This implies that geopolitical vulnerability is cyclical, and the constitutional legal tools required to manage it must remain permanently available to the state.4
This exhaustive debate underscores a vital, enduring principle in Islamic law: the critical distinction between the text (nass) and the context of its application (manat). The divine text mandating the category is eternal, but the contextual reality determining the existence of a "heart needing reconciliation" fluctuates endlessly based on macro-level power dynamics, state security, and the psychological state of targeted demographics.4
Governance and Statecraft: Al-Mawardi’s Constitutional Theory
The operationalization of Zakat, and specifically the mu'allafatu qulubuhum category, cannot be fully grasped without examining classical Islamic constitutional theory. The paramount text in this domain is Al-Ahkam al-Sultaniyyah (The Ordinances of Government), authored by the brilliant Shafi'i jurist and political theorist Judge Abu al-Hasan al-Mawardi (d. 450 AH / 1058 CE).28 Born in Basra and serving as the Chief Justice (Qadi al-Qudat) in Baghdad during a highly volatile period, Al-Mawardi acted as a roving ambassador for the Abbasid Caliph al-Qaim bi Amr Allah, navigating the treacherous power struggles between the declining Abbasid Caliphate and the rising military dominance of the Buwayhids and Seljuks.29
In Al-Ahkam al-Sultaniyyah, Al-Mawardi systematically codified the comprehensive workings of Islamic governance across twenty exhaustive chapters.28 The scope of his treatise demonstrates the all-encompassing nature of the Islamic state, with chapters covering the contract of the Imamate, the appointment of ministers, the authority of the judiciary, the regulations of land, the distribution of loot, and crucially, the administration of Zakat and charitable institutions (Chapter Eleven), as well as the imposition of Jizya and Kharaj taxes (Chapter Thirteen).28
Within this grand theoretical framework, Al-Mawardi, alongside contemporary scholars like Al-Juwayni and Al-Ghazali, argued that the Imamate is a communal obligation designed to uphold legitimate leadership, maintain social cohesion, and actualize the higher objectives of the Sharia.31 The collection and distribution of Zakat is framed not as localized charity, but as a sovereign function of the state. Al-Mawardi's specific analysis of the mu'allafatu qulubuhum—where he categorized them into four distinct groups ranging from those with weak certainty to massive tribal alliances—embeds this category deeply within the broader responsibilities of the Caliphate.4 The Imam is obligated to utilize state resources, including designated Zakat funds, to manage complex political alliances, neutralize ideological threats, and project state power, framing the mu'allafatu qulubuhum not merely as passive charity recipients, but as subjects of sophisticated, highly calibrated statecraft.28
Modern Theoretical Frameworks: Yusuf al-Qaradawi and the State Apparatus
For centuries, during the zenith of Islamic imperial power (from the Umayyads through the Abbasids to the Ottomans), the practical application of al-mu'allafatu qulubuhum remained largely theoretical or dormant, as the state rarely found itself in the existential vulnerability that characterized the early Medinan period. However, the catastrophic collapse of the Caliphate, the advent of European colonialism, and the resulting fragmentation of the Muslim world in the 19th and 20th centuries catalyzed a profound revival of this category among contemporary jurists who recognized the shifting global power dynamics.
The foremost modern theoretician to revitalize and systematically re-engineer this concept for the contemporary era was the late Egyptian scholar Dr. Yusuf al-Qaradawi in his magnum opus, Fiqh al-Zakah.2 First published over three decades ago, this two-volume treatise remains unparalleled in its comprehensiveness and represents a monumental effort to make classical rules understandable to modern policy-makers.2 Recognizing the profound socio-economic and political weaknesses of the modern Muslim world, al-Qaradawi argued that the global Ummah is arguably in a state of ideological and political vulnerability comparable to the early Meccan and Medinan periods. Consequently, he advocated for a robust, state-led institutional reactivation of the mu'allafatu qulubuhum category.6
Al-Qaradawi’s framework transitioned the category from the ancient realm of tribal diplomacy to the modern arena of institutional support and ideological defense. He proposed that modern governments must take an active, highly interventionist role in Zakat collection.34 He emphasized that governments should not rely solely on voluntary Zakat payments, but must actively collect Zakat from physical material wealth (al-a'yan) and deduct Zakat directly from the savings of the Muslim community in banks if they have reached the designated threshold (nisab) and time period (haul).34
By centralizing the collection of these immense funds, the state can efficiently utilize the mu'allafatu qulubuhum category not merely as defensive bribes, but as an offensive tool for mass propagation (Da'wah) and socio-economic integration.35 This involves providing substantial financial support to new converts who face socio-economic ostracization, funding ideological defense mechanisms, and engaging in large-scale public relations initiatives to soften anti-Islamic sentiment on a global scale.27 Al-Qaradawi's paradigm emphasizes that the collection and distribution of Zakat is fundamentally a macroeconomic state responsibility, requiring modern bureaucratic efficiency to achieve the macroscopic goals of the nation.34
Contemporary Controversies: PACs, Lobbying, and Western Democracies
The modernization of the mu'allafatu qulubuhum concept has not been without intense, polarizing controversy. As Muslim populations permanently established themselves in Western liberal democracies—where political power is not held by tribal warlords but by elected officials and corporate interests—a novel jurisprudential debate emerged regarding the utilization of Zakat funds for political lobbying, advocacy, and funding Political Action Committees (PACs).11
The Proponents' Argument: Redefining the 'Illah
In Western contexts, certain contemporary scholars and activists have issued legal edicts (fatwas) attempting to aggressively expand the definition of al-mu'allafah qulubuhum to justify funneling restricted Zakat money directly into political campaigns, media advocacy, and lobbying organizations.11 The logic driving this expansion is deeply utilitarian. Proponents argue that the Prophet Muhammad gave massive wealth to tribal chieftains specifically to secure political influence and protect the Ummah.11 In modern democratic systems, they argue, authority is not centralized in a single coercing ruler, but is instead diffused across vast electoral bodies, legislators, and media institutions.11 Therefore, they contend, the 'illah (ratio legis) of securing political influence to benefit Muslims dictates that Zakat should be spent on modern equivalents: politicians, media campaigns, and political action committees.11 To support this, proponents frequently cite the classical Hanbali scholar Ibn Qudamah, who defined the mu'allafah as "the leaders who have authority in their communities," whose faith might be strengthened or whose evil minimized.11
The Traditionalist Critique: Safeguarding Zakat from Politicization
This expansive, modernizing interpretation has been met with fierce resistance from traditional jurists, who argue that it represents a dangerous misappropriation of divinely restricted funds, effectively transforming a sacred pillar of Islam into a secular, general-purpose political slush fund.11 The traditionalist counter-arguments dismantle the proponents' claims on several highly technical jurisprudential grounds:
Conflation of Spoils of War and Restricted Zakat: The most critical juristic error identified by traditionalists is the fundamental failure to distinguish between vastly different categories of state revenue. The massive wealth distributed by the Prophet at the Battle of Hunayn—the primary historical evidence used by PAC proponents—was derived from the spoils of war (ghanīmah and fay'), not from the Zakat treasury.11 The Prophet possessed absolute discretionary financial authority (taṣarruf al-imām) over war spoils to distribute as he saw fit for state interests. Zakat, conversely, consists of divinely restricted entitlements explicitly earmarked for eight specific categories of recipients in the Quran.11 Drawing an analogy between the discretionary use of war spoils and the restricted distribution of Zakat constitutes an invalid analogy (qiyās maʿ al-fāriq al-muʾaththir).11
Physical Recipients vs. Abstract Entities: In the strict architecture of Zakat, mu'allafah describes a specific, physical condition (ṣifah) of a human being—an individual whose literal heart is actually being reconciled.11 It does not, under any classical reading, describe an abstract policy objective, an organizational entity, a corporation, or a political campaign designed to influence abstract public opinion.11 Redefining al-mu'allafah qulubuhum from a category of physical recipients to a functional policy tool for political influence is classified as a severe juristic error (fasād al-waḍʿ).11
Miscontextualization of Classical Texts: Traditionalists argue that citing Ibn Qudamah's reference to "leaders who have authority" is anachronistic and academically flawed. The classical Arabic text refers specifically to "obeyed chiefs within their tribes" (al-sādah al-muṭāʿūn fī ʿashāʾirihim), pointing directly to pre-modern tribal settings featuring inherited, kin-based, and highly coercive authority.11 This specific socio-political reality cannot be flattened to fit the modern sociological notion of symbolic "community leaders" or democratically elected officials whose influence is merely partial, procedural, or aspirational.11 Classical Hanbali scholars placed severe restrictions on this category; for example, Imam Abu Ali al-Hashimi wrote that the category did not exist in his time, and Al-Buhuti clarified in Kashshaf al-Qina' that anyone who is not literally an obeyed chief within their specific clan cannot be given Zakat for reconciliation, even if their evil is feared.11
Consequently, contemporary traditional fiqh guidance strongly advises Muslims in the West to exercise extreme caution when donating. Donors are instructed to rigorously screen charities to ensure Zakat is not diverted to political campaigns, lobbying, or media advocacy under the guise of mu'allafatu qulubuhum, insisting instead on clear, individual-based Shari'i eligibility.11
Humanitarian Aid and Non-Muslim Refugees
A parallel, highly relevant modern debate involves the disbursement of Zakat to non-Muslims facing severe humanitarian crises, such as natural disasters, famine, or mass displacement. Historically, as noted, the Shafi'i school strictly prohibited giving Zakat to non-Muslims, a view seemingly supported by the overarching Prophetic tradition that Zakat is taken from the rich among the Muslims and given to the poor among them.26
However, faced with the realities of global humanitarian crises, some modern institutional bodies have sought to navigate this restriction by invoking the latent mu'allafatu qulubuhum category.12 Certain contemporary scholars argue that in the context of global peace initiatives, disaster relief, and massive poverty eradication programs, distributing Zakat to non-Muslims serves the specific, historically validated purpose of advancing peace, discouraging war, and showcasing the inherent mercy of Islamic teachings—objectives that perfectly align with the linguistic and historical intent of "reconciling hearts".12
Fatwas issued by authoritative bodies such as Dar Al-Ifta Al-Missriyyah in Egypt, and utilized by international humanitarian bodies like the UNHCR, have carefully navigated these classical restrictions. They sometimes rely on the critical distinction between mandatory Zakat and voluntary charity (sadaqah), emphasizing that the latter is unequivocally permissible for non-Muslims as long as they are not at war with Muslims.36 When Zakat itself is utilized for non-Muslim refugees, it is tightly restricted to the explicit intention of ta'lif al-qulub for sympathetic non-Muslims, executed under exceptional circumstances and often requiring the involvement of local religious authorities to ensure compliance.12 Some scholars, echoing classical minority views like those of Ibn Al Munzir, note broader flexibilities, though the majority caution that this should remain a policy for exceptional, dire circumstances rather than the norm.36
Institutionalizing Ta'lif: The Malaysian Administrative Paradigm
The transition of al-mu'allafatu qulubuhum from classical legal theory to modern bureaucratic administration is perhaps best exemplified by the highly sophisticated, state-managed Zakat system in Malaysia. The Lembaga Zakat Selangor (LZS), the official Zakat institution in the state of Selangor, provides an extraordinarily structured, socio-economic development framework specifically targeting this category, locally referred to as Asnaf Mualaf (new converts to Islam).13
In the Malaysian context, the interpretation of mu'allafatu qulubuhum eschews geopolitical bribery in favor of the intense social, psychological, and economic stabilization of individuals who have recently embraced Islam.13 Recognizing that conversion often results in severe socio-economic ostracization, loss of family support, and immediate financial vulnerability, the state steps in to act as a comprehensive surrogate support system. The approach of Zakat Selangor is remarkably holistic, moving far beyond mere cash handouts to structured, long-term capability building.13
The Asnaf Development Blueprint and Core Programs
Under the strategic Asnaf Development Blueprint, Zakat Selangor aims to transition mualaf from a state of critical dependency to complete independence, ultimately aiming for them to achieve Mukalaf status—where they are emotionally, spiritually, and financially stable enough to seamlessly integrate into the community and eventually become Zakat contributors themselves.13 This is achieved through a multi-tiered system of interventions:
Immediate Financial Relief: Recognizing the acute shock of conversion, new Muslims in Selangor are provided an immediate monthly allowance (typically RM 500) designed to run for up to five years, ensuring basic economic survival during their most vulnerable transition period.39
Protection and Shelter Infrastructure: Zakat Selangor operates specialized, gazetted protection centers to house converts facing immediate danger. Baitus Salam, transferred to their administration in 2017, provides temporary placement under the Restricted Areas Act 1959, offering food, healthcare, and physical protection for those rejected by their families or facing external threats.13 Similarly, Bait Al-Mawaddah serves as a safe refuge for new Muslims, helping to realign their emotional and social directions while safeguarding their new faith.13
Structured Education and Spiritual Development: The core of the Malaysian model is mandatory, highly structured education. Zakat funds finance the Mualaf Asnaf Induction Course (KIAM), which provides immediate post-conversion orientation, introducing them to support agencies and their new rights.13 This is followed by the Fardu Ain Classes for Mualaf (KFAM), a long-term, multi-level curriculum (Levels 1 to 3) covering fundamental theology (Tawhid) and jurisprudence (Fiqh) to reinforce self-identity and confidence.13 Furthermore, specialized centers like Baitul Hikmah in Ulu Yam offer advanced courses in leadership, women's fiqh, motivation, and prayer improvement (Tahsin Solat), alongside deep psychological counseling and character development (tarbiah).13
Assessment and Graduation: The bureaucratic maturity of this system is evident in the implementation of the Had Ta’lif Assessment Examination. Passing this evaluation is a critical, formal milestone, signifying that the individual's heart has been successfully reconciled and stabilized. Upon passing, they are no longer classified as legally vulnerable or needy (fakir/miskin); they transition from being Zakat beneficiaries to recognized alumni, fully integrated into the socio-religious fabric of the community.13
The Selangor model represents a profound operationalization of the mu'allafatu qulubuhum category. By treating the "reconciliation of hearts" as a measurable, programmatic objective with specific educational milestones and financial safety nets, the institution effectively bridges the massive gap between ancient theological mandates and the rigorous demands of modern social welfare administration.13
Corporate Zakat and Global Financial Reporting Standards
While the primary focus of al-mu'allafatu qulubuhum remains on the recipient and the ideological objectives of the state, the modernization of Zakat also involves highly complex regulations regarding how it is generated and accounted for at a global institutional level. To fund large-scale ta'lif initiatives—such as the massive infrastructure in Malaysia or global humanitarian relief—massive pools of capital are required. Organizations like the Accounting and Auditing Organization for Islamic Financial Institutions (AAOIFI) and the International Islamic Fiqh Academy (IIFA) have issued rigorous standards to regulate how Islamic financial institutions calculate and report Zakat liabilities.41
The issuance of AAOIFI Financial Accounting Standard (FAS) 39, titled "Financial Reporting for Zakah" (effective January 1, 2023), provides critical guidance on the recognition, presentation, and disclosure of Zakat attributable to relevant stakeholders.41 This standard ensures that even if an institution is not legally required to pay Zakat, it must identify and disclose the amount due, bringing transparency to corporate Islamic finance.41
Furthermore, IIFA Resolution No. 143 (1/16), issued in Dubai, addressed the complex realities of modern banking by ruling on Zakat for restricted investment accounts, security deposits, and end-of-service benefits.42 The resolution mandated that owners of investment accounts must pay Zakat on balances and profits, regardless of withdrawal restrictions.42 Crucially, it ruled that the "Margin of seriousness" (Hamish al Jidiyyah—amounts paid as security for covering potential risks in transactions) and initial securities for entering bids are deductible from Zakat-liable assets for the institution, but the owners of such securities must include them in their own Zakat calculations.42 While critics note that treating corporate entities identically to individual wealth in traditional law can create confusion regarding ownership and the ultimate zakatable base, these standardized reporting mechanisms are absolutely essential.44 The formalization of corporate Zakat ensures that the modern Islamic state or designated NGO possesses the transparent fiscal capacity to execute large-scale ta'lif (reconciliation) projects.
Conclusion
The evolution of al-mu'allafatu qulubuhum from the tribal battlefields of 7th-century Arabia to the boardrooms of modern Western charities and the bureaucratic offices of Southeast Asian welfare states is a profound testament to the remarkable elasticity and depth of Islamic jurisprudence. As one of the eight divinely mandated categories of Zakat, it serves a function that is entirely distinct from mere poverty alleviation; it is a complex instrument of socio-political engineering, diplomatic leverage, psychological stabilization, and communal integration.
The historical trajectory of this category—activated by the Prophet Muhammad to secure unprecedented geopolitical stability through massive wealth transfers, famously suspended by Umar ibn al-Khattab when the overwhelming geopolitical strength of the state rendered such tribal appeasement unnecessary, and maintained in a state of contextual readiness by classical jurists—highlights the highly sophisticated nature of the Islamic legal concept of the effective cause ('illah). The divine law remains eternal, but its practical application is intimately and inextricably tied to the socio-political realities and vulnerabilities of the era.
In the contemporary landscape, this category remains a fascinating battleground of jurisprudential interpretation. The controversial attempt to utilize these restricted funds for Political Action Committees in Western democracies reveals the inherent, ongoing tension between maintaining the strict textual integrity of Zakat as an individual entitlement and the utilitarian desire to leverage religious funds for collective political influence. Conversely, the highly structured integration programs in Malaysia demonstrate how the ancient spirit of "reconciling hearts" can be successfully and beautifully institutionalized to provide psychological, spiritual, and economic safety nets for vulnerable new converts. Ultimately, the continuous study and application of al-mu'allafatu qulubuhum exemplifies the dual nature of the Islamic socio-economic system: it remains a profound act of spiritual devotion inextricably bound to the pragmatic survival, expansion, and cohesion of the global Muslim community.
Works cited
Zakat In Islam - Full Guide, accessed May 24, 2026, https://www.sahlah.net/blog/zakat-in-islam---full-guide
FIQH AL ZAKAH /VOLUME 1 - A platform for studying and downloading Books and Articles about Islam, accessed May 24, 2026, https://islamic-sources.com/books/fiqh-al-zakah
Surah Taubah Ayat 60 (9:60 Quran) With Tafsir - My Islam, accessed May 24, 2026, https://myislam.org/surah-taubah/ayat-60/
WHO ARE THE MU'ALLAFATU QULUBUHUM (THOSE WHO ARE GIVEN ZAKAT TO BRING THEIR HEARTS NEAR) ? | UNITY, accessed May 24, 2026, https://unity1.store/2024/04/22/who-are-the-muallafatu-qulubuhum-those-who-are-given-zakat-to-bring-their-hearts-near/
Who receives Zakat? - NZF, accessed May 24, 2026, https://nzf.org.uk/knowledge/who-receives-zakat/
Fiqh Al Zakah: Regulations & Philosophy | PDF | Religion & Spirituality - Scribd, accessed May 24, 2026, https://www.scribd.com/doc/176582319/Fiqh-of-Zakah-by-Yusuf-Al-Qardawi-2
MUALLAFA AL-QULUB (THOSE WHOSE HEARTS ARE TO BE RECONCILED WITH ISLAM), accessed May 24, 2026, https://questionsonislam.com/article/muallafa-al-qulub-those-whose-hearts-are-be-reconciled-islam
The Share of (Al-Muallafa Qulubuhum) and Its Contemporary Applications - Figshare, accessed May 24, 2026, https://manara.qnl.qa/articles/thesis/The_Share_of_Al-Muallafa_Qulubuhum_and_Its_Contemporary_Applications/28007492
The History of the Four Khulafaa - Umar - r.a - the principles of his rule & his life in society, accessed May 24, 2026, https://muslimcentral.com/abdullah-chaabou-the-history-of-the-four-khulafaa-umar-r-a-the-principles-of-his-rule-his-life-in-society
ZAKAT DISTRIBUTION POLICY OF UMAR BIN KHATTAB AND COVID-19 CRISIS - Journal IAIN Manado, accessed May 24, 2026, https://journal.iain-manado.ac.id/index.php/TJEBI/article/viewFile/1184/930
Zakāt Is Not a PAC — Revisiting al-Mu'allafah Qulūbuhum in ..., accessed May 24, 2026, https://theoryinpractice.medium.com/zak%C4%81t-is-not-a-pac-revisiting-al-muallafah-qul%C5%ABbuhum-in-modern-fiqh-d4a7d7eb2b6d
Can You Give Zakat to Non-Muslims? - Al Mustafa Welfare Trust, accessed May 24, 2026, https://www.almustafatrust.org/islamic-resources/can-you-give-zakat-to-non-muslims/
Asnaf Development – Lembaga Zakat Selangor, accessed May 24, 2026, https://www.zakatselangor.com.my/en/asnaf-development/
Lisan al-Arab - Wikipedia, accessed May 24, 2026, https://en.wikipedia.org/wiki/Lisan_al-Arab
Lisan al-Arab: A Masterpiece of Arabic Lexicography - Islamonweb English, accessed May 24, 2026, https://en.islamonweb.net/lisan-al-arab-a-masterpiece-of-arabic-lexicography
Arabic Language Learning Tools - OneWorld Now!, accessed May 24, 2026, https://oneworldnow.org/2014/12/16/arabic-language-learning-tools/
The Importance of Had Ta'lif and Social Support in Enhancing the Well-being of Muallaf in the State of Selangor - RSIS International, accessed May 24, 2026, https://rsisinternational.org/journals/ijriss/articles/the-importance-of-had-talif-and-social-support-in-enhancing-the-well-being-of-muallaf-in-the-state-of-selangor/
Tafseer Ibn Katheer Surah At-Taubah Verse 60 - Word of Allah, accessed May 24, 2026, https://www.wordofallah.com/tafseer/9/60
ZAKAT GIVING TO NON- MUSLIMS: MUFTIS' ATTITUDES IN ARAB AND NON-ARAB COUNTRIES 0F - IU ScholarWorks, accessed May 24, 2026, https://scholarworks.iu.edu/iupjournals/index.php/muslimphilanthropy/article/download/4889/345/21608
Is Zakat for 'Those Whose Hearts Are Attracted (to the Faith)' Still Applicable?, accessed May 24, 2026, https://seekersguidance.org/answers/zakat/is-zakat-for-those-whose-hearts-are-attracted-to-the-faith-still-applicable/
Fiqh-us-Sunnah, Volume 3: The Recipients of Zakah, accessed May 24, 2026, https://www.islamicstudies.info/subjects/fiqh/fiqh_us_sunnah/fus3_46.html
Giving Zakah to a non-Muslim - إسلام ويب, accessed May 24, 2026, https://www.islamweb.net/en/fatwa/86852/giving-zakah-to-a-non-muslim
Schools and Classifications of Fiqh: A Guide to Understanding the Diversity of Islamic Law, accessed May 24, 2026, https://ejournal.seaninstitute.or.id/index.php/jecoa/article/download/5229/4199
What is the origin of each school of thought (Hanafi, Shafi'i, Maliki, Hanbali)? Did they create their own rules or were they based on existing beliefs? - Quora, accessed May 24, 2026, https://www.quora.com/What-is-the-origin-of-each-school-of-thought-Hanafi-Shafii-Maliki-Hanbali-Did-they-create-their-own-rules-or-were-they-based-on-existing-beliefs
Hanafi? Maliki? Shafi'? Hanbali? Explaining Sunni Schools of Thought | Dr. Shabir Ally, accessed May 24, 2026, https://www.youtube.com/watch?v=XO0RS5x71MM
Is It Permissible to Give Zakat to Non-Muslims? - SeekersGuidance, accessed May 24, 2026, https://seekersguidance.org/answers/zakat/is-it-permissible-to-give-zakat-to-non-muslims/
The Muallafat al-Qulūb “conciliating people's hearts” Category of Zakāh - Mathabah, accessed May 24, 2026, https://mathabah.org/the-muallafat-al-qulub-conciliating-peoples-hearts-category-of-zakah/
Al-Ahkam al-Sultaniyyah - Wikipedia, accessed May 24, 2026, https://en.wikipedia.org/wiki/Al-Ahkam_al-Sultaniyyah
Al-Ahkam as-Sultaniyyah | The Laws of Islamic Governance | Mawardi - Kalamullah.Com, accessed May 24, 2026, https://www.kalamullah.com/ahkam-sultaniyyah.html
Apprehending Al-Mawardi's Theory of Imamate - ijhsss, accessed May 24, 2026, https://www.ijhsss.com/files/06.-Adil-Hussain-Bhat.pdf
Shāfiʿī Political Theorists on the Imamate: Māwardī, Juwaynī, and Ghazālī - Ummatics, accessed May 24, 2026, https://ummatics.org/shafi%CA%BFi-jurists-ii/
FIQH AL ZAKAH - Monzer Kahf, accessed May 24, 2026, https://monzer.kahf.com/books/english/fiqhalzakah_vol1.pdf
Zakat Calculation : Based on Fiqh-uz-Zakat by Yusuf al-Qaradawi 9780860375678, accessed May 24, 2026, https://dokumen.pub/zakat-calculation-based-on-fiqh-uz-zakat-by-yusuf-al-qaradawi-9780860375678.html
Revitalization of The Collection of Zakat Funds in Indonesia: An Explanation from Yusuf Al-Qaradawi's Fiqh Al-Zakah | Journal of Islamic Economics Lariba, accessed May 24, 2026, https://journal.uii.ac.id/JIELariba/article/view/26635
Fiqh Islami Framework As A Da'wah Medium In Addressing Muallaf Issues In The Malaysian Context, accessed May 24, 2026, https://kwpublications.com/papers_submitted/9927/fiqh-islami-framework-as-a-dawah-medium-in-addressing-muallaf-issues-in-the-malaysian-context.pdf
Dar al-Ifta al-Missriyyah | Egypt - - UNHCR, accessed May 24, 2026, https://zakat.unhcr.org/blog/en/fatwa/dar-al-ifta-al-missriyyah
Is it permissible for Zakat funds to be spent on non-Muslim beneficiaries? - Al-Qalam, accessed May 24, 2026, https://alqalam.org.uk/is-it-permissible-for-zakat-funds-to-be-spent-on-non-muslim-beneficiaries-can-they-be-considered-muallafati-quloobuhum-in-this-context/
Asnaf Development Centre - Lembaga Zakat Selangor, accessed May 24, 2026, https://www.zakatselangor.com.my/en/asnaf-development-centre/
The Role of Zakat and Success Factor for Muallaf Conditions: An Analysis in Selangor, Malaysia - Ulum Islamiyyah, accessed May 24, 2026, https://uijournal.usim.edu.my/index.php/uij/article/download/58/63/220
(PDF) MUALLAF DEVELOPMENT THROUGH ZAKAT DISTRIBUTION AND PROGRAMMES IN SELANGOR, MALAYSIA: AN OVERVIEW - ResearchGate, accessed May 24, 2026, https://www.researchgate.net/publication/257812237_MUALLAF_DEVELOPMENT_THROUGH_ZAKAT_DISTRIBUTION_AND_PROGRAMMES_IN_SELANGOR_MALAYSIA_AN_OVERVIEW
AAOIFI issues Financial Accounting Standard 39 “Financial Reporting for Zakah” officially in Arabic, accessed May 24, 2026, https://aaoifi.com/announcement/aaoifi-issues-financial-accounting-standard-39-financial-reporting-for-zakah-officially-in-arabic/?lang=en
Zakāh on Restricted Accounts, Islamic Insurance Companies, Security Deposits, and End-Of-Service Benefits, accessed May 24, 2026, https://iifa-aifi.org/en/32897.html
AAOIFI issues Financial Accounting Standard (FAS) 39 “Financial Reporting for Zakah”, accessed May 24, 2026, https://aaoifi.com/announcement/aaoifi-issues-financial-accounting-standard-fas-39-financial-reporting-for-zakah/?lang=en
Analysing the AAOIFI Sharīʿah standard on zakat - IDEAS/RePEc, accessed May 24, 2026, https://ideas.repec.org/a/eme/jmlcpp/jmlc-10-2020-0117.html
Analysing the AAOIFI Sharīʿah standard on zakat - ResearchGate, accessed May 24, 2026, https://www.researchgate.net/publication/349085347_Analysing_the_AAOIFI_Shariah_standard_on_zakat
